### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by gordio** [OmniSharp/omnisharp-sublime#104]
```
Traceback (most recent call last):
  File "/Users/gordio/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 303, in on_activated
    callback.on_activated(v)
  File "/Users/gordio/Library/Application Support/Sublime Text 3/Packages/OmniSharp/listeners/server_runner.py", line 12, in on_activated
    omnisharp.create_omnisharp_server_subprocess(view)
  File "/Users/gordio/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/omnisharp.py", line 247, in create_omnisharp_server_subprocess
    solution_path = current_solution_or_project_json_folder(view) #current_solution_or_folder(view)
  File "/Users/gordio/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/helpers.py", line 73, in current_solution_or_project_json_folder
    parentpath = sublime.active_window().folders()[0] #assume parent folder is opened that contains all project folders eg/Web,ClassLib,Tests
IndexError: list index out of range
```
And in "realtime" I check:
```
>>> sublime.active_window().folders()
[]
```

**Comment by jchannon** [comment]
Is this because you've just one csharp file open and not a folder with a project in it?

**Comment by gordio** [comment]
Yep. It's when Sublime opened from file/terminal/programm (like Unity3D or Alfred).
And path exist only if sublime open project or directory (from terminal, ex `subl ./`).

**Comment by jchannon** [comment]
yeah i figured people would be editing stuff for whole projects.

i guess it should handle single files too.

if the folders()[0] is empty it should return the path of the single open
file. if you fancy contributing feel free as I dont have time to look at
this right now

**Comment by jchannon** [comment]
PR for this is #105

**Comment by jchannon** [comment]
Should be done now with 1.9.1 release

**Comment by Karlheinzniebuhr** [comment]
same issue here
