### ISSUE TITLE
Autocomplete sporadically stops working

### ISSUE THREAD

**Issue by juzzbott** [OmniSharp/omnisharp-sublime#123]
The auto-complete feature seems to sporadically crashes, and it seems to be communicating to the omnisharpserver.

I'm currently using the "Roslyn" branch of the OmniSharp-sublime plugin, as the default package used to show annoying syntax errors (that weren't actually errors, as the project would still build).

I _have_ had auto-complete working previously, but I've made no changed to sublime for it to stop working. 

I'm currently using Linux Mint 17, and I've changed the default shell from dash to bash to ensure that kvm.sh runs correctly at login.

Error message shown in the sublime console:

```
OmniSharp Error:

response: "/home/justin/Development/juzzbott"
request: http://localhost:33186/autocomplete
======== request params ======== 
 b'{"WantReturnType": true, "line": "38", "wordToComplete": "Try", "WantSnippet": true, "buffer": "using System;\\nusing System.Collections.Generic;\\nusing System.Linq;\\n\\nusing MongoDB.Bson;\\nusing MongoDB.Driver;\\n\\nusing Juzzbott.Models;\\n\\nnamespace Juzzbott.Services\\n{\\n    public class BlogService\\n    {\\n\\n        // The mongo client\\n        private MongoClient _mongoDb;\\n\\n        public BlogService () \\n    \\t{\\n            _mongoDb = new MongoClient();\\n        }\\n\\n        public IList<BlogPost> GetLatest(int count) \\n        {\\n\\n            // Get the latest blog entries\\n\\n\\n            // return the blog posts\\n            return null;\\n\\n        }\\n\\n        public BlogPost GetSinglePost(string id) \\n        {\\n            throw new NotImplementedException();\\n\\n            Int32.Try\\n        }\\n\\n    }\\n}", "column": "22", "WantMethodHeader": true, "filename": "/home/justin/Development/juzzbott/src/Juzzbott/Services/BlogService.cs"}'
[2015-03-03 17:23:12,360 - WARNING  - OmniSharp.lib.urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))': /autocomplete
[2015-03-03 17:23:12,361 - WARNING  - OmniSharp.lib.urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))': /autocomplete
[2015-03-03 17:23:12,362 - WARNING  - OmniSharp.lib.urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))': /autocomplete
Traceback (most recent call last):
  File "/home/justin/.config/sublime-text-3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 529, in urlopen
    body=body, headers=headers)
  File "/home/justin/.config/sublime-text-3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 334, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "./http/client.py", line 1065, in request
  File "./http/client.py", line 1103, in _send_request
  File "./http/client.py", line 1061, in endheaders
  File "./http/client.py", line 906, in _send_output
  File "./http/client.py", line 844, in send
  File "/home/justin/.config/sublime-text-3/Packages/OmniSharp/lib/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/home/justin/.config/sublime-text-3/Packages/OmniSharp/lib/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/justin/.config/sublime-text-3/Packages/OmniSharp/lib/urllib3/util/connection.py", line 87, in create_connection
    raise err
  File "/home/justin/.config/sublime-text-3/Packages/OmniSharp/lib/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/justin/.config/sublime-text-3/Packages/OmniSharp/lib/omnisharp.py", line 38, in run
    response = http.urlopen('POST', url, body=data)
  File "/home/justin/.config/sublime-text-3/Packages/OmniSharp/lib/urllib3/poolmanager.py", line 153, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/justin/.config/sublime-text-3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 595, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/justin/.config/sublime-text-3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 595, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/justin/.config/sublime-text-3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 595, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/justin/.config/sublime-text-3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 575, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/home/justin/.config/sublime-text-3/Packages/OmniSharp/lib/urllib3/util/retry.py", line 271, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
OmniSharp.lib.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=33186): Max retries exceeded with url: /autocomplete (Caused by ProtocolError('Connection aborted.', ConnectionRefusedError(111, 'Connection refused')))
======== response ========
None
None
CALLBACK_ERROR
```

**Comment by jchannon** [comment]
Looks like the server isnt running.

**Comment by Gronis** [comment]
I have the same error, I just got it working and every 5 minutes, OmniSharp stops working and I have to restart sublime to restart OmniSharp

**Comment by tim241** [comment]
Closing due to inactivity.
