### ISSUE TITLE
Just not working, even with latest update

### ISSUE THREAD

**Issue by coderangerdan** [OmniSharp/omnisharp-sublime#158]
I am sorry, but when i first tried this a few days ago it worked, then mysteriously it stopped working a few hours later (I think Sublime3 updated); I have tried the things posted here for chmod and such forth which didn't help, then I noticed it just updated and i tried again, still no luck, I have uninstalled and reinstalled the package and still not working.

I get this whenever I try to do an intellisense popup:

    response: "/Users/coderangerdan/Documents/Projects/c#-vnext/SimpleTest/Program.sln"
    request: http://localhost:51103/autocomplete
    ======== request params ======== 
     b'{"WantSnippet": true, "WantReturnType": true, "column": "11", "WantMethodHeader": true, "wordToComplete": "", "filename": "/Users/coderangerdan/Documents/Projects/c#-vnext/SimpleTest/Program.cs", "buffer": "using System;\\npublic class Program\\n{\\n\\tpublic static void Main()\\n\\t{\\n\\t\\tConsole.WriteLine(\\"Hello World\\");\\n\\t\\tConsole.WriteLine(\\"testing 23qeq\\");\\n\\t}\\n}\\n", "line": "7"}'
    Traceback (most recent call last):
      File "/Users/coderangerdan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 529, in urlopen
        
      File "/Users/coderangerdan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 334, in _make_request
        
      File "./http/client.py", line 1065, in request
      File "./http/client.py", line 1103, in _send_request
      File "./http/client.py", line 1061, in endheaders
      File "./http/client.py", line 906, in _send_output
      File "./http/client.py", line 844, in send
      File "/Users/coderangerdan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connection.py", line 155, in connect
        conn = self._new_conn()
      File "/Users/coderangerdan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connection.py", line 134, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "/Users/coderangerdan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/util/connection.py", line 87, in create_connection
        if err is not None:
      File "/Users/coderangerdan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/util/connection.py", line 78, in create_connection
        sock.connect(sa)
    ConnectionRefusedError: [Errno 61] Connection refused

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/coderangerdan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/omnisharp.py", line 38, in run
        
      File "/Users/coderangerdan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/poolmanager.py", line 153, in urlopen
        kw['assert_same_host'] = False
      File "/Users/coderangerdan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 595, in urlopen
        
      File "/Users/coderangerdan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 595, in urlopen
        
      File "/Users/coderangerdan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 595, in urlopen
        
      File "/Users/coderangerdan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/connectionpool.py", line 575, in urlopen
        
      File "/Users/coderangerdan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/urllib3/util/retry.py", line 271, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    OmniSharp.lib.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=51103): Max retries exceeded with url: /autocomplete (Caused by ProtocolError('Connection aborted.', ConnectionRefusedError(61, 'Connection refused')))

Can you give any advice, sorry to ask but I haven't been able to find a solution. I even tried running OmniSharp.exe with mono from the package folder and I also get an error (don't know if its related):

    00000044 Using solution path /Users/coderangerdan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/PrebuiltOmniSharpServer
    00000045 Using config file /Users/coderangerdan/Library/Application Support/Sublime Text 3/Packages/OmniSharp/PrebuiltOmniSharpServer/config.json
    Monodoc documentation tree could not be loaded.System.InvalidOperationException: Sequence contains no elements
      at System.Linq.Enumerable.First[String] (IEnumerable`1 source) [0x00000] in <filename unknown>:0 
      at MonoDevelop.Projects.HelpService.InitializeHelpTree () [0x00000] in <filename unknown>:0 
    00000996 OmniSharp server is listening

**Comment by jchannon** [comment]
Looks like you are trying it for vnext apps.

You will have to clone the git repo and use the roslyn branch

**Comment by coderangerdan** [comment]
Nope just a simple nine line file:
		using System;
		public class Program
		{
			public static void Main()
			{
				Console.WriteLine("Hello World");
				Console.WriteLine("testing 23qeq");
			}
		}

**Comment by jchannon** [comment]
with a solution?

do you see mono-sgen in activity monitor when a csharp file is activated?

kill sublime, kill mono sgen processes, open sublime, open a cs file, check mono sgen is running, try formatting a document to see if it works

**Comment by coderangerdan** [comment]
Ah, I found a package.json file (dunno where that came from, perhaps yeoman) which must have made it think it was a vNext version; I deleted that and changed my sublime project to `"solution_file": "./"` and it now works.

Thanks for your help, and much apologies for wasting your time!

**Comment by jchannon** [comment]
no worries
