### ISSUE TITLE
Exception thrown when executing a Run Unit Test command

### ISSUE THREAD

**Issue by nathanboktae** [OmniSharp/omnisharp-sublime#194]
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "/Users/nblack/Library/Application Support/Sublime Text 3/Packages/OmniSharp/commands/type_lookup.py", line 19, in run
    omnisharp.get_response(self.view, '/typelookup', self._handle_typelookup, params)
  File "/Users/nblack/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/omnisharp.py", line 84, in get_response
    timeout = int(get_settings(view, 'omnisharp_response_timeout'))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

The setting is there in `OmniSharp.sublime-settings` in the package folder

``` json
{
    "omnisharp_response_timeout": 100,
    "omnisharp_auto_start": true,
    "omnisharp_server_config_location":"",
    "omnisharp_onsave_codecheck": true,
    "omnisharp_onsave_showwarningwindows":true,
    "omnisharp_onsave_showerrorwindows":true
}
```

**Comment by igorkulman** [comment]
Happens to me on Windows when trying to do anything (autocomplete, format document, go to definition, etc.)

**Comment by aschuhardt** [comment]
Getting this in Ubuntu 18 whenever I try to do anything, as reported above.

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 672, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "/home/aschuhardt/.config/sublime-text-3/Packages/OmniSharp/listeners/completion.py", line 37, in on_query_completions
    omnisharp.get_response(view, '/autocomplete', self._complete, params)
  File "/home/aschuhardt/.config/sublime-text-3/Packages/OmniSharp/lib/omnisharp.py", line 84, in get_response
    timeout = int(get_settings(view, 'omnisharp_response_timeout'))
TypeError: int() argument must be a string or a number, not 'NoneType'
solution path: /home/aschuhardt/Projects/fulgens-console/FulgensConsole.Example
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 462, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 552, in <lambda>
    run_callback('on_post_save', callback, lambda: callback.on_post_save(v))
  File "/home/aschuhardt/.config/sublime-text-3/Packages/OmniSharp/listeners/add_file_to_project.py", line 14, in on_post_save
    omnisharp.get_response(view, '/addtoproject', self._handle_addtoproject)
  File "/home/aschuhardt/.config/sublime-text-3/Packages/OmniSharp/lib/omnisharp.py", line 84, in get_response
    timeout = int(get_settings(view, 'omnisharp_response_timeout'))
TypeError: int() argument must be a string or a number, not 'NoneType'
file changed
['/home/aschuhardt/Projects/fulgens-console/FulgensConsole.Example/Game.cs']
already_bound_solution:/home/aschuhardt/Projects/fulgens-console/FulgensConsole.Example
already_bound_solution:/home/aschuhardt/Projects/fulgens-console/FulgensConsole.Example
already_bound_solution:/home/aschuhardt/Projects/fulgens-console/FulgensConsole.Example
solution path: /home/aschuhardt/Projects/fulgens-console/FulgensConsole.Example
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 672, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "/home/aschuhardt/.config/sublime-text-3/Packages/OmniSharp/listeners/completion.py", line 37, in on_query_completions
    omnisharp.get_response(view, '/autocomplete', self._complete, params)
  File "/home/aschuhardt/.config/sublime-text-3/Packages/OmniSharp/lib/omnisharp.py", line 84, in get_response
    timeout = int(get_settings(view, 'omnisharp_response_timeout'))
TypeError: int() argument must be a string or a number, not 'NoneType'
solution path: /home/aschuhardt/Projects/fulgens-console/FulgensConsole.Example
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 672, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "/home/aschuhardt/.config/sublime-text-3/Packages/OmniSharp/listeners/completion.py", line 37, in on_query_completions
    omnisharp.get_response(view, '/autocomplete', self._complete, params)
  File "/home/aschuhardt/.config/sublime-text-3/Packages/OmniSharp/lib/omnisharp.py", line 84, in get_response
    timeout = int(get_settings(view, 'omnisharp_response_timeout'))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by tim241** [comment]
Closing due to having outdated information.
