### ISSUE TITLE
Path to solution file error

### ISSUE THREAD

**Issue by andreyz** [OmniSharp/omnisharp-sublime#213]
Just opened a Unity project folder with .sln file present. OmniSharp used to work just a week ago on exactly the same folder.

Now I get the following error:

```
Please specify a path to the solution file in your sublime-project file or delete it
```

**Comment by robbert229** [comment]
Could you please post the log? Also what OS are you running and what version of mono are you using?

**Comment by andreyz** [comment]
OS X:
```
10.11.4 Beta (15E39d)
```
Mono:
```
Mono JIT compiler version 4.2.2 (Stable 4.2.2.30/996df3c Wed Feb 10 13:36:17 PST 2016)
```
Sublime console:
```
omnisharp plugin_loaded
project file %s found /Users/andrey/Projects/Clients/Isotop/Radioapan/Radioapan.sublime-project
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 231, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 327, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/Users/andrey/Library/Application Support/Sublime Text 3/Packages/OmniSharp/listeners/server_runner.py", line 12, in on_activated
    omnisharp.create_omnisharp_server_subprocess(view)
  File "/Users/andrey/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/omnisharp.py", line 107, in create_omnisharp_server_subprocess
    solution_path = current_solution_filepath_or_project_rootpath(view)
  File "/Users/andrey/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/helpers.py", line 33, in current_solution_filepath_or_project_rootpath
    raise ValueError('Please specify a path to the solution file in your sublime-project file or delete it')
ValueError: Please specify a path to the solution file in your sublime-project file or delete it
project file %s found /Users/andrey/Projects/Clients/Isotop/Radioapan/Radioapan.sublime-project
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 231, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 327, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/Users/andrey/Library/Application Support/Sublime Text 3/Packages/OmniSharp/listeners/server_runner.py", line 12, in on_activated
    omnisharp.create_omnisharp_server_subprocess(view)
  File "/Users/andrey/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/omnisharp.py", line 107, in create_omnisharp_server_subprocess
    solution_path = current_solution_filepath_or_project_rootpath(view)
  File "/Users/andrey/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/helpers.py", line 33, in current_solution_filepath_or_project_rootpath
    raise ValueError('Please specify a path to the solution file in your sublime-project file or delete it')
ValueError: Please specify a path to the solution file in your sublime-project file or delete it
```

**Comment by v2k** [comment]
Did you find a solution for this?

**Comment by tim241** [comment]
omnisharp-roslyn has been updated, if this is still an issue, please open a new issue with new details,

Closing
