### ISSUE TITLE
Periodic crash using Omnisharp Sublime

### ISSUE THREAD

**Issue by danmosemsft** [OmniSharp/omnisharp-sublime#224]
Sublime 3 and Omnisharp (installed from pkg manager) v1.9.6 

```
"System.NotSupportedException: Specified method is not supported.
   at Mono.Cecil.PE.ImageReader.ReadArchitecture()
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImageFrom(Stream stream)
   at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at ICSharpCode.NRefactory.TypeSystem.CecilLoader.LoadAssemblyFile(String fileName)
   at OmniSharp.Solution.Project.<LoadAssembly>m__0(String file)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at OmniSharp.Solution.Project.LoadAssembly(String assemblyFileName)
   at OmniSharp.Solution.Project.AddReference(String reference)
   at OmniSharp.Solution.CSharpProject..ctor(ISolution solution, Logger logger, String folderPath, IFileSystem fileSystem)
   at OmniSharp.Solution.CSharpFolder.LoadSolution()
   at OmniSharp.Program
.StartServer(String solutionPath, String clientPathMode, Int32 port, Verbosity verbosity, String configLocation, Int32 hostPID)
   at OmniSharp.Program.Main(String[] args)"
```

**Comment by tim241** [comment]
Is this still an issue in the latest build?
