### ISSUE TITLE
OmniSharp Ubuntu installation python errors, opening .cs file error. Not working. It seems server not starting or something due to python errors.

### ISSUE THREAD

**Issue by idchlife** [OmniSharp/omnisharp-sublime#262]
# Platform
- [x] Linux
- [ ] Windows
- [ ] OSX

# Type
- [x] This is an issue
- [ ] This is a feature request
- [ ] Other

# Checklist
- [ ] It hasn't been fixed in the latest master
- [x] I can reproduce this issue in a fresh Sublime Text install without other extensions

# Versions
output of `mono --version`:
```
Mono JIT compiler version 6.4.0.198 (tarball Tue Sep 24 01:21:28 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```
output of `msbuild /version`:
```
Microsoft (R) Build Engine version 16.3.0-ci for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

16.300.19.41901%
```

# Details
What's the bug?

After opening .cs file - error, not working.
Error:
```python
omni_port:51367
RAISE_OMNI_SHARP_LAUNCHER_EXCEPTION:TypeError("'NoneType' object is not iterable",)
```

Also, right after installation this error:

```python
ignored packages updated to: []
reloading plugin OmniSharp.OmniSharpSublime
omnisharp plugin_loaded
Traceback (most recent call last):
  File "/snap/sublime-text/69/opt/sublime_text/sublime_plugin.py", line 196, in load_module
    m.plugin_loaded()
  File "/home/idchlife/.config/sublime-text-3/Packages/OmniSharp/OmniSharpSublime.py", line 25, in plugin_loaded
    omni_exe_path = get_omni_path(active_view())
  File "/home/idchlife/.config/sublime-text-3/Packages/OmniSharp/lib/helpers.py", line 85, in get_omni_path
    relative_omni_path = get_omni_active(view).get("path")
  File "/home/idchlife/.config/sublime-text-3/Packages/OmniSharp/lib/helpers.py", line 70, in get_omni_active
    for server in servers:
TypeError: 'NoneType' object is not iterable
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

# How-To
How do I reproduce this issue?

Install Sublime Text 3.2.1, 3207 on Ubuntu Linux:

![image](https://user-images.githubusercontent.com/4563032/65870040-17714c00-e384-11e9-980f-6707aba76ae8.png)

Install OmniSharp, try to open Unity project.

I think it's important to mention, VSCode on same system with OmniSharp is working fine

**Comment by idchlife** [comment]
Guys? Issue exist even on new installation Lubuntu, latest version.

Same errors.

Does anybody know hot to fix it and use C# in sublime?
