### ISSUE TITLE
Keep getting a 503 connecting to omnisharp server

### ISSUE THREAD

**Issue by mburbea** [OmniSharp/omnisharp-sublime#79]
I just installed the omnisharp plugin but everytime I type I get the following error::
  File "C:\Users\mburbea\AppData\Roaming\Sublime Text 3\Packages\OmniSharp\lib\omnisharp.py", line 38, in run
    response = urllib.request.urlopen(url, data, timeout)
  File "./urllib/request.py", line 156, in urlopen
  File "./urllib/request.py", line 475, in open
  File "./urllib/request.py", line 587, in http_response
  File "./urllib/request.py", line 507, in error
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 692, in http_error_302
  File "./urllib/request.py", line 475, in open
  File "./urllib/request.py", line 587, in http_response
  File "./urllib/request.py", line 513, in error
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 595, in http_error_default
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
======== response ========
None
CALLBACK_ERROR
TERMINATE_OMNI_SHARP
exit_omni_sharp_launcher:C

Any idea how to correct this issue?

**Comment by JohnPoison** [comment]
Hi. I guess I have similar issue. I worked on project and I changed the git repository for it. So I moved it to the new location. Now when I'm trying to open "Navigate to" I keep getting error:
already_bound_solution:/Users/fateev/unity/matr/match3.sln
project file found
response: /Users/fateev/unity/matr/match3.sln
request: http://localhost:62334/currentfilemembersasflat
======== request params ======== 
...
Traceback (most recent call last):
  File "./urllib/request.py", line 1248, in do_open
  File "./http/client.py", line 1065, in request
  File "./http/client.py", line 1103, in _send_request
  File "./http/client.py", line 1061, in endheaders
  File "./http/client.py", line 906, in _send_output
  File "./http/client.py", line 844, in send
  File "./http/client.py", line 822, in connect
  File "./socket.py", line 435, in create_connection
  File "./socket.py", line 426, in create_connection
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fateev/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/omnisharp.py", line 41, in run
    response = opener.open(url, data, timeout)
  File "./urllib/request.py", line 469, in open
  File "./urllib/request.py", line 487, in _open
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 1268, in http_open
  File "./urllib/request.py", line 1251, in do_open
urllib.error.URLError: <urlopen error [Errno 61] Connection refused>
======== response ========
None
CALLBACK_ERROR
None

Project at the previous location  /Users/fateev/unity/match3/match3.sln keeps working properly

already_bound_solution:/Users/fateev/unity/match3/match3.sln
project file found
response: /Users/fateev/unity/match3/match3.sln
request: http://localhost:62583/currentfilemembersasflat
======== request params ======== 
...
======== response ========
[{"LogLevel":null,"FileName":"/Users/fateev/unity/match3/Assets/Scripts/GameSpecificScripts/UserState/Building.cs","Line":28,"Column":5,"EndLine":28,"EndColumn":34,"Text":"baseReward"},{"LogLevel":null,"FileName":"/Users/fateev/unity/match3/Assets/Scripts/GameSpecificScripts/UserState/Building.cs","Line":8,"Column":1,"EndLine":119,"EndColumn":2,"Text":"Building"},{"LogLevel":null,"FileName":"/Users/fateev/unity/match3/Assets/Scripts/GameSpecificScripts/UserState/Building.cs","Line":42,"Column":5,"EndLine":45,"EndColumn":6,"Text":"Building()"},{"LogLevel":null,"FileName":"/Users/fateev/unity/match3/Assets/Scripts/GameSpecificScripts/UserState/Building.cs","Line":102,"Column":5,"EndLine":110,"EndColumn":6,"Text":"ConsumeReward()"},
...

**Comment by jchannon** [comment]
I"m closing this, if still an issue after 1.8.1 release please let me know
