### ISSUE TITLE
Unhelpful error message if config.json fails to parse

### ISSUE THREAD

**Issue by lostfictions** [OmniSharp/omnisharp-sublime#87]
This threw me for a loop for a while. Didn't dig deep enough to figure out where this is happening, but if you modify OmniSharpServer's config.json and it fails to parse correctly, instead of printing an error in Sublime's console it just refuses a connection with a really baffling error message, something like this:

```
Request: http://localhost:51778/gotodefinition
======== request params ======== 
 {"column": "35", "line": "38", /* some fields omitted */ }
Traceback (most recent call last):
  File "./urllib/request.py", line 1248, in do_open
  File "./http/client.py", line 1065, in request
  File "./http/client.py", line 1103, in _send_request
  File "./http/client.py", line 1061, in endheaders
  File "./http/client.py", line 906, in _send_output
  File "./http/client.py", line 844, in send
  File "./http/client.py", line 822, in connect
  File "./socket.py", line 435, in create_connection
  File "./socket.py", line 426, in create_connection
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/(user)/Library/Application Support/Sublime Text 3/Packages/OmniSharp/lib/omnisharp.py", line 38, in run
    response = urllib.request.urlopen(url, data, timeout)
  File "./urllib/request.py", line 156, in urlopen
  File "./urllib/request.py", line 469, in open
  File "./urllib/request.py", line 487, in _open
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 1268, in http_open
  File "./urllib/request.py", line 1251, in do_open
urllib.error.URLError: <urlopen error [Errno 61] Connection refused>
======== response ========
None
CALLBACK_ERROR
TERMINATE_OMNI_SHARP
...
```

**Comment by JavadocMD** [comment]
Just got bit by this one myself. Errant comma in the config. When Sublime would go to set up the OmniSharp server, I'd immediately get a Windows "OmniSharp.exe has stopped working" crash dialog. If there's no programmatic solution, perhaps adding some troubleshooting documentation would be enough.
