### ISSUE TITLE
Issue when building

### ISSUE THREAD

**Issue by ctartamella** [OmniSharp/omnisharp-sublime#94]
I installed both Kulture and OmniSharp into Sublime via package control.  After adding the solution path to my project, I get the following error message in the console:

building
project file is : D:\Topaz\Topaz.sublime-project
response: D:\(Path Obscured, but correct)\MacroRecorder.csproj
Traceback (most recent call last):
  File "C:\DevTools\Sublime Text 3\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "C:\DevTools\Sublime Text 3\Data\Packages\OmniSharp\commands\build_project.py", line 17, in run
    options[buildtype]()
  File "C:\DevTools\Sublime Text 3\Data\Packages\OmniSharp\commands\build_project.py", line 20, in build
    self.getbuild('build')
  File "C:\DevTools\Sublime Text 3\Data\Packages\OmniSharp\commands\build_project.py", line 31, in getbuild
    omnisharp.get_response(self.view, '/buildtarget', self._handle_build, params)    
  File "C:\DevTools\Sublime Text 3\Data\Packages\OmniSharp\lib\omnisharp.py", line 67, in get_response
    callback(None)
  File "C:\DevTools\Sublime Text 3\Data\Packages\OmniSharp\commands\build_project.py", line 34, in _handle_build
    self.buildcommand = data["Command"]
TypeError: 'NoneType' object is not subscriptable

I did a little digging, and I'm not sure if the server is starting correctly or not.  The call stack suggests that there is nothing added to the server_ports list.

**Comment by ctartamella** [comment]
I think I had some index files locked.  It seems to be working now.  Thanks!
